name: e_commerce_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7   #splash screen ar jonna
  smooth_page_indicator: ^1.2.1  #page ar change ta jano bujha jay sata bujhar jonna
  lottie: ^3.3.2  #Onboarding, splash, loader, success, empty states — সব জায়গায় use করা যায়।
  get: ^4.7.2
  iconsax: ^0.0.8 # for more icon explore flaticon or icons8
  carousel_slider: ^5.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logo/
    - assets/animations/
    - assets/logo/
    - assets/images/
    - assets/icons/categories/
    - assets/banners/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800
